# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100, verbose_name='Nome')),
                ('image_src_text', models.CharField(max_length=100, verbose_name='Caminho da imagem')),
                ('amount', models.IntegerField(default=1, verbose_name='Quantidade')),
            ],
        ),
    ]
