# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170712_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateitem',
            name='image_src_text',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Caminho da imagem'),
        ),
    ]
