# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170712_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateitem',
            name='image_src_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Caminho da imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_src_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho da imagem'),
        ),
    ]
